export class Course {
  name:
    | string[]
    | ['Medicina']
    | ['Odontologia']
    | ['Engenharia Civil']
    | ['Direito']
    | ['Arquitetura e Urbanismo']
    | ['Farmácia']
    | ['Nutrição']
    | ['Psicologia']
    | ['Cinema']
    | ['Jornalismo']
    | ['Enfermagem']
    | ['Biomedicina']
    | ['Publicidade e Propaganda']
    | ['Administração']
    | ['Agronomia']
    | ['Gastronomia']
    | ['Ciências Contábeis']
    | ['Comércio Exterior']
    | ['Filosofia']
    | ['Relações Internacionais']
    | ['Fisioterapia']
    | ['Sistemas de Informação']
    | ['Medicina Veterinária']
    | ['Pedagogia']
    | ['História']
    | ['Geografia']
    | ['Gestão de Recursos Humanos']
    | ['Sistemas de Informação']
    | ['Gestão Financeira']
    | ['Marketing']
    | ['Logística']
    | ['Química']
    | ['Física']
    | ['Análise e Desenvolvimento de Sistemas'] = ['Administração'];
}
