# -*- coding: utf-8 -*-
"""Biometria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19jpVE8lh3hklofTkvxhHzqR4tTX3Uo7E
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
import os

test_original = cv2.imread("finger-print.png")
cv2_imshow(test_original)
cv2.waitKey(0)
cv2.destroyAllWindows()

match_points = []
for file in [file for file in os.listdir("./database")]:
    print(file)
    fingerprint_database_image = cv2.imread("./database/"+file)
    
    sift = cv2.xfeatures2d.SIFT_create()
    
    keypoints_1, descriptors_1 = sift.detectAndCompute(test_original, None)
    print(keypoints_1)
    keypoints_2, descriptors_2 = sift.detectAndCompute(fingerprint_database_image, None)
    print(keypoints_2)
    matches = cv2.FlannBasedMatcher(dict(algorithm=1, trees=10), 
    dict()).knnMatch(descriptors_1, descriptors_2, k=2)
    
   
    for p, q in matches:
      if p.distance < 0.1*q.distance:
          match_points.append(p)

keypoints = 0
if len(keypoints_1) <= len(keypoints_2):
  keypoints = len(keypoints_1)      
else:
  keypoints = len(keypoints_2)
print(keypoints)  
print(len(match_points))
if (len(match_points) / keypoints)>0.3:
  print("% match: ", len(match_points) / keypoints * 100)
  print("Figerprint ID: " + str(file)) 
  result = cv2.drawMatches(test_original, keypoints_1, fingerprint_database_image, keypoints_2, match_points, None) 
  result = cv2.resize(result, None, fx=2.5, fy=2.5)
  cv2_imshow(result)
  cv2.waitKey(0)