# -*- coding: utf-8 -*-
"""Esteganografia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MmlbROjIAmUXTIa-KrZ0HJEuLp5JViOY
"""

from stegano import lsb

secret = lsb.hide("monalisa.png", "Leonardo")

secret.save("leonardo.png")

mensagem = lsb.reveal("leonardo.png")

print(mensagem)